# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline:
  # - name: spellcheck.SpellCheck
  - name: SpacyNLP
  - name: SpacyTokenizer
  - name: SpacyEntityExtractor
  - name: RegexFeaturizer
  - name: CRFEntityExtractor
    features:
      [
        ["low", "title", "upper"],
        [
          "bias",
          "low",
          "prefix5",
          "prefix2",
          "suffix5",
          "suffix3",
          "suffix2",
          "upper",
          "title",
          "digit",
          "pattern",
        ],
        ["low", "title", "upper"],
      ]

  # - name: WhitespaceTokenizer
  # - name: "DucklingHTTPExtractor"
  #   url: "http://localhost:8000"
  #   dimensions: ["email"]
  #   timeout: 3
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: FormPolicy
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: MappingPolicy
